pypro/aperitivos/urls.py
from django.urls import path
from pypro.aperitivos.views import video, index


app_name = 'aperitivos'

urlpatterns = [
    path('', index, name='index'),
    path('<slug:slug>', video, name='video'),
]

pypro/base/urls.py
from django.urls import path
from pypro.base.views import home


app_name = 'base'

urlpatterns = [
    path('', home, name='home'),
]

pypro/modulos/urls.py
from django.urls import path
from pypro.modulos import views


app_name = 'modulos'

urlpatterns = [
    path('<slug:slug>', views.detalhe, name='detalhe'),
    path('aulas/<slug:slug>', views.aula, name='aula'),
    path('', views.indice, name='indice'),
]

pypro/turmas/urls.py
from django.urls import path
from pypro.turmas import views


app_name = 'turmas'

urlpatterns = [
    path('', views.indice, name='indice'),
]

pypro/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),
    path('modulos/', include('pypro.modulos.urls')),
    path('turmas/', include('pypro.turmas.urls')),
]

if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls)))

pypro/aperitivos/models.py
from django.db import models
from django.urls import reverse


class Video(models.Model):
    titulo = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32)
    vimeo_id = models.CharField(max_length=32)
    creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))

    def __str__(self):
        return f'Video: {self.titulo}'

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email, and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % self.first_name
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/modulos/models.py
from django.db import models
from django.urls import reverse
from ordered_model.models import OrderedModel


# Create your models here.
class Modulo(OrderedModel):
    titulo = models.CharField(max_length=64)
    publico = models.TextField()
    descricao = models.TextField()
    slug = models.SlugField(unique=True)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:detalhe', kwargs={'slug': self.slug})


class Aula(OrderedModel):
    titulo = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    modulo = models.ForeignKey('Modulo', on_delete=models.PROTECT)
    order_with_respect_to = 'modulo'
    vimeo_id = models.CharField(max_length=32)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:aula', kwargs={'slug': self.slug})

pypro/turmas/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Turma(models.Model):
    nome = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64)
    inicio = models.DateField()
    fim = models.DateField()
    alunos = models.ManyToManyField(get_user_model(), through='Matricula')

    def __str__(self):
        return self.nome


class Matricula(models.Model):
    data = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    turma = models.ForeignKey(Turma, on_delete=models.CASCADE)

    class Meta:
        unique_together = [['usuario', 'turma']]
        ordering = ['turma', 'data']

pypro/aperitivos/views.py
from django.shortcuts import render, get_object_or_404
from pypro.aperitivos.models import Video


def video(request, slug):
    video = get_object_or_404(Video, slug=slug)
    return render(request, 'aperitivos/video.html', context={'video': video})


def index(request):
    # TODO: Refactorar regra de negócio para um modulo de fachada (facade).
    videos = Video.objects.order_by('creation').all()
    return render(request, 'aperitivos/index.html', context={'videos': videos})

pypro/base/views.py
from django.shortcuts import render


# Create your views here.
from django.urls import reverse


def home(request):
    contexto = {
        'aperitivos': reverse('aperitivos:index')
    }
    return render(request, 'base/home.html', context={'contexto': contexto})

pypro/modulos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from pypro.modulos import facade


def indice(request):
    modulos = facade.listar_modulos_com_aulas()
    return render(request, 'modulos/indice.html', context={'modulos': modulos})


def detalhe(request, slug):
    modulo = facade.encontrar_modulo(slug)
    aulas = facade.encontrar_aulas_por_modulo_ordenadas(modulo)
    return render(request, 'modulos/modulo_detalhe.html', context={'modulo': modulo, 'aulas': aulas})


@login_required
def aula(request, slug):
    aula = facade.encontrar_aula(slug)
    return render(request, 'modulos/aula_detalhe.html', context={'aula': aula})

pypro/turmas/views.py
from django.shortcuts import render


# Create your views here.
def indice(request):
    return render(request, 'turmas/indice.html')

pypro/aperitivos/templates/aperitivos/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Python Pro{% endblock title %}

{% block body %}
	<div class="container">
		<div class="row pb-3 pt-3">
			<div class="col-md-12 mb-3">
                <h1>Lista de Vídeos Aperitivo</h1>
		    </div>
			<div class="col-md-12 mb-3">
				<ol>
                {% for video in videos %}
					<li><a href="{{ video.get_absolute_url }}">{{ video.titulo | default:"Faltando Título"}}</a></li>
				{% empty %}
					<li>Nenhum vídeo disponível</li>
				{% endfor %}
				</ol>
		    </div>
		</div>
	</div>
{% endblock body %}

pypro/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Python Pro{% endblock title %}

{% block body %}
	<div class="container">
		<div class="row pb-3 pt-3">
			<div class="col-md-12 mb-3">
                <h1>{{ video.titulo }}</h1>
		    </div>
            <div class="embed-container mw-100">
                <iframe src="https://player.vimeo.com/video/{{ video.vimeo_id }}" width="640" height="361" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
		    </div>
		</div>
	</div>
{% endblock body %}

pypro/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Python Pro{% endblock title %}</title>

    <meta name="description" content="{% block description %}Plataforma de cursos Python Pro{% endblock description %}">
    <meta name="author" content="Thiago 'undersfx' Rodrigues">

	<link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
	<script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

  </head>
  <body>

	  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		  <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
			  <ul class="navbar-nav mr-auto">
				  <li class="nav-item dropdown">
					  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						  Módulos
					  </a>
					  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
						  {% for modulo in MODULOS %}
						  <a class="dropdown-item" href="{{modulo.get_absolute_url}}">{{modulo.titulo}}</a>
						  {% endfor %}
					  </div>
				  </li>
			  </ul>
		  {% if user.is_authenticated %}
			  <ul class="navbar-nav">
				  <li class="nav-item dropdown">
					  <a class="nav-link dropdown-toggle" href="#" id="loginDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						  {{ user.first_name }}
					  </a>
					  <div class="dropdown-menu" aria-labelledby="loginDropdown">
							<div class="dropdown-item">
								<a class="btn btn-danger" href="{% url 'logout' %}">Sair</a>
					  		</div>
					  </div>
				  </li>
			  </ul>
		  {% else %}
			  <a class="btn btn-light my-2" href="{% url 'login' %}">Entrar</a>
		  {% endif %}
		  </div>
	  </nav>

	{% block body %}
	{% endblock body %}

  <footer class="main-footer mt-3 pt-4 text-light">
	  <div class="container">
		  <div class="row">
			  <div class="col">
				<h3>Entre em contato</h3>
				  <address>
					  <a href="tel:+5511993335283" class="text-light">+55 11 99-333-5283</a>
					  <br/>
					  <a href="mailto:thiago.rfr@hotmail.com" class="text-light">thiago.rfr@hotmail.com</a>
				  </address>
			  </div>
		  </div>
	  </div>

	  <div class="rights pb-2 pt-2">
	  <div class="container">
		  <div class="row">
			  <div class="col">
				{% now 'Y' %} Python Pro. Todos os direitos reservados.
			  </div>
		  </div>
	  </div>
	  </div>
  </footer>

  </body>
</html>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Python Pro - Home{% endblock title %}

{% block body %}
	<div class="container">
		<div class="row pb-3 pt-3">
			<div class="col-md-12">
				<!-- BEGIN Mailchimp Signup Form -->
				<form class="row gx-3 gy-2 align-items-center" action="https://github.us7.list-manage.com/subscribe/post?u=c5b5390c0b10165e2653f4748&amp;id=076b59ef11" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank" novalidate>
					<div class="col-auto">
						<h4>Entre na lista de espera</h4>
					</div>
					<div class="col-sm-3 pb-1">
						<div class="input-group">
							<div class="input-group-text">Nome:</div>
							<input class="form-control" type="text" value="" name="FNAME" id="mce-FNAME" placeholder="Nome">
						</div>
					</div>
					<div class="col-sm-3 pb-1">
						<div class="input-group">
							<div class="input-group-text">Email*:</div>
							<input class="form-control required" type="email" value="" name="EMAIL" id="mce-EMAIL" placeholder="Email">
						</div>
					</div>
					<div id="mce-responses" class="clear">
						<div class="response" id="mce-error-response" style="display:none"></div>
						<div class="response" id="mce-success-response" style="display:none"></div>
					</div>
					<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    				<div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c5b5390c0b10165e2653f4748_076b59ef11" tabindex="-1" value=""></div>
					<div class="col-auto">
						<input type="submit" value="Quero aprender Python" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary">
					</div>
				</form>
				<!-- END Mailchimp Signup Form -->
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="jumbotron" style="margin-bottom:1rem;">
					<h2>Curso de Python com Thiago Rodrigues</h2>
					<a href="{{ contexto.aperitivos }}">Confira os vídeos aperitivos gratuitos</a>
				</div>

				<div class="row">
					<div class="col-md-12">
						<p>
							<img src="{% static 'img/python_cobra.jpg' %}" class="img-fluid" alt="python-cobra" style="width:100%">
						</p>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<h5 class="card-header">
								Mais detalhes sobre o instrutor
							</h5>
							<div class="card-body">
								<p class="card-text">
									<img src="{% static 'img/thiago-rodrigues.jpg' %}" class="img-thumbnail float-left mr-3"
										 width="200" height="200" alt="Foto de Thiago Rodrigues" />
									Mussum Ipsum, cacilds vidis litro abertis. Todo mundo vê os porris que eu tomo,
									mas ninguém vê os tombis que eu levo! Interagi no mé, cursus quis, vehicula ac nisi.
									Si num tem leite então bota uma pinga aí cumpadi! Interessantiss quisso pudia ce
									receita de bolis, mais bolis eu num gostis.
									<p></p>
									<a href="https://www.linkedin.com/in/trfrodrigues/" target="_blank">LinkedIn</a> /
									<a href="https://undersfx.github.io/about/" target="_blank">Blog</a> /
									<a href="https://github.com/undersfx" target="_blank">Github</a>
								</p>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
{% endblock body %}

pypro/modulos/templates/modulos/aula_detalhe.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Python Pro{% endblock title %}

{% block body %}
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="/">Home</a></li>
			<li class="breadcrumb-item"><a href="{{aula.modulo.get_absolute_url}}">{{aula.modulo.titulo}}</a></li>
			<li class="breadcrumb-item active" aria-current="page">{{aula.titulo}}</li>
		</ol>
	</nav>

	<div class="container">
		<div class="row pb-3">
			<div class="col-md-12 mb-3">
                <h1>{{ aula.titulo }}</h1>
		    </div>
            <div class="embed-container mw-100">
                <iframe src="https://player.vimeo.com/video/{{ aula.vimeo_id }}" width="640" height="361" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
		    </div>
		</div>
	</div>
{% endblock body %}

pypro/modulos/templates/modulos/indice.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}{{modulo.titulo}}{% endblock title %}
{% block description %}Página com informações sobre o módulo {{modulo.titulo}}{% endblock description %}

{% block body %}
{% for modulo in modulos %}
	<div class="container">
		<div class="row pb-3 pt-3">
			<div class="col-md-12 mb-3">
                <h1>{{modulo.titulo}}</h1>

				<dl>
					<dt>Público</dt>
					<dd>{{modulo.publico}}</dd>
					<dt>Descrição</dt>
					<dd>{{modulo.descricao}}</dd>
				</dl>

				<h2>Aulas</h2>
				<ol>
					{% for aula in modulo.aulas %}
						<li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
					{% endfor %}
				</ol>
		    </div>
		</div>
	</div>
{% endfor %}
{% endblock body %}

pypro/modulos/templates/modulos/modulo_detalhe.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}{{modulo.titulo}}{% endblock title %}
{% block description %}Página com informações sobre o módulo {{modulo.titulo}}{% endblock description %}

{% block body %}
	<div class="container">
		<div class="row pb-3 pt-3">
			<div class="col-md-12 mb-3">
                <h1>{{modulo.titulo}}</h1>

				<dl>
					<dt>Público</dt>
					<dd>{{modulo.publico}}</dd>
					<dt>Descrição</dt>
					<dd>{{modulo.descricao}}</dd>
				</dl>

				<h2>Aulas</h2>
				<ol>
					{% for aula in aulas %}
						<li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
					{% endfor %}
				</ol>
		    </div>
		</div>
	</div>
{% endblock body %}

pypro/turmas/templates/turmas/indice.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}{{modulo.titulo}}{% endblock title %}
{% block description %}Página com todas as turmas do curso {{modulo.titulo}}{% endblock description %}

{% block body %}
{% for modulo in modulos %}
	<div class="container">
		<div class="row pb-3 pt-3">
			<div class="col-md-12 mb-3">
                <h1>{{modulo.titulo}}</h1>

				<dl>
					<dt>Público</dt>
					<dd>{{modulo.publico}}</dd>
					<dt>Descrição</dt>
					<dd>{{modulo.descricao}}</dd>
				</dl>

				<h2>Aulas</h2>
				<ol>
					{% for aula in modulo.aula_set.all %}
						<li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
					{% endfor %}
				</ol>
		    </div>
		</div>
	</div>
{% endfor %}
{% endblock body %}